### ISSUE TITLE
(1.6.0) Cannot read property 'vcRef' of undefined in InjectionService code

### ISSUE THREAD

**Issue by alanpurple** [swimlane/ng2d3#82]
EXCEPTION: Cannot read property 'vcRef' of undefinedErrorHandler.handleError @ core.umd.js:2834
core.umd.js:2839 ORIGINAL STACKTRACE:ErrorHandler.handleError @ core.umd.js:2839
core.umd.js:2840 TypeError: Cannot read property 'vcRef' of undefined
    at InjectionService.getRootViewContainerRef (http://localhost:1337/lib/ng2d3/ng2d3.js:1322:53)
    at InjectionService.appendNextToRoot (http://localhost:1337/lib/ng2d3/ng2d3.js:1337:29)
    at TooltipDirective.injectComponent (http://localhost:1337/lib/ng2d3/ng2d3.js:2116:42)
    at eval (http://localhost:1337/lib/ng2d3/ng2d3.js:2064:33)
    at ZoneDelegate.invokeTask (http://localhost:1337/lib/zone.js/zone.js:265:35)
    at Object.onInvokeTask (http://localhost:1337/lib/@angular/core/bundles/core.umd.js:5963:41)
    at ZoneDelegate.invokeTask (http://localhost:1337/lib/zone.js/zone.js:264:40)
    at Zone.runTask (http://localhost:1337/lib/zone.js/zone.js:154:47)
    at ZoneTask.invoke (http://localhost:1337/lib/zone.js/zone.js:335:33)
    at data.args.(anonymous function) (http://localhost:1337/lib/zone.js/zone.js:970:25)ErrorHandler.handleError @ core.umd.js:2840
Subscriber.ts:241Uncaught TypeError: Cannot read property 'vcRef' of undefined(…)

**Comment by alanpurple** [comment]
actually there is no "_hostElement" property in ComponentRef.
@angular/core 2.2.0

**Comment by alanpurple** [comment]
I thinks this is due to change in angular 2.2.0, verified using plunker

**Comment by alanpurple** [comment]
change in 2.2.0

AppElement -> ViewContainer

no "hostElement" property in  ApplicationRef

**Comment by amcdnl** [comment]
This is a 2.2.0 breaking change https://github.com/angular/angular/issues/9293

**Comment by amcdnl** [comment]
Fixed in https://github.com/swimlane/ng2d3/commit/06bf502364cfe08822c7cd858b8ebc3f90d217ab
